# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/simonadi/Documents/ensimag/msiam/project/Modelling-Project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/simonadi/Documents/ensimag/msiam/project/Modelling-Project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/simonadi/Documents/ensimag/msiam/project/Modelling-Project/CMakeFiles /home/simonadi/Documents/ensimag/msiam/project/Modelling-Project/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/simonadi/Documents/ensimag/msiam/project/Modelling-Project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named libFingerPrintsrc

# Build rule for target.
libFingerPrintsrc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libFingerPrintsrc
.PHONY : libFingerPrintsrc

# fast build rule for target.
libFingerPrintsrc/fast:
	$(MAKE) -f src/CMakeFiles/libFingerPrintsrc.dir/build.make src/CMakeFiles/libFingerPrintsrc.dir/build
.PHONY : libFingerPrintsrc/fast

#=============================================================================
# Target rules for targets named libFingerPrinth

# Build rule for target.
libFingerPrinth: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libFingerPrinth
.PHONY : libFingerPrinth

# fast build rule for target.
libFingerPrinth/fast:
	$(MAKE) -f include/CMakeFiles/libFingerPrinth.dir/build.make include/CMakeFiles/libFingerPrinth.dir/build
.PHONY : libFingerPrinth/fast

demo/main.o: demo/main.cpp.o

.PHONY : demo/main.o

# target to build an object file
demo/main.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/demo/main.cpp.o
.PHONY : demo/main.cpp.o

demo/main.i: demo/main.cpp.i

.PHONY : demo/main.i

# target to preprocess a source file
demo/main.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/demo/main.cpp.i
.PHONY : demo/main.cpp.i

demo/main.s: demo/main.cpp.s

.PHONY : demo/main.s

# target to generate assembly for a file
demo/main.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/demo/main.cpp.s
.PHONY : demo/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... edit_cache"
	@echo "... libFingerPrintsrc"
	@echo "... libFingerPrinth"
	@echo "... demo/main.o"
	@echo "... demo/main.i"
	@echo "... demo/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

